// Generated by `supabase gen types typescript` once the schema lands.
// Until then, this is a placeholder so server/client code can import
// `Database` without breaking the build.
export type Database = Record<string, never>;
